version: '3.9'

services:
  postgres:
    image: postgres:15-alpine
    container_name: usuarios-postgres
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: 123456
    ports:
      - "5432:5432"

  rabbitmq:
    image: rabbitmq:3-management-alpine
    container_name: usuarios-rabbit
    environment:
      RABBITMQ_DEFAULT_USER: admin
      RABBITMQ_DEFAULT_PASS: password
    ports:
      - "5672:5672"
      - "15672:15672"

  eureka-server:
    image: eurekaserver:latest
    container_name: eureka-server
    ports:
      - "8761:8761"

  usuarios-service:
    build: .
    container_name: usuarios-service
    environment:
      DB_USER: postgres
      DB_PASS: 123456
      JWT_SECRET: libreria-rocky-jwt-key-para-microservicios-usuarios-2025
      RABBIT_USER: admin
      RABBIT_PASS: password
      CONFIG_GIT_URI: https://github.com/JrP1478/libreriarocky-config.git
      CONFIG_SERVER_USER: configuser
      CONFIG_SERVER_PASSWORD: config123
      EUREKA_HOST: eureka-server
      SERVER_PORT: 8081
    ports:
      - "8081:8081"
    depends_on:
      - postgres
      - rabbitmq
      - eureka-server
