version: '3.9'

services:
  postgres:
    image: postgres:15-alpine
    container_name: usuarios-postgres
    environment:
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASS}
    ports:
      - "5432:5432"

  rabbitmq:
    image: rabbitmq:3-management-alpine
    container_name: usuarios-rabbit
    environment:
      RABBITMQ_DEFAULT_USER: ${RABBIT_USER}
      RABBITMQ_DEFAULT_PASS: ${RABBIT_PASS}
    ports:
      - "5672:5672"
      - "15672:15672"

  eureka-server:
    image: eurekaserver:latest  # si ya tienes la imagen de Eureka
    container_name: eureka-server
    ports:
      - "8761:8761"

  usuarios-service:
    build: .
    container_name: usuarios-service
    environment:
      DB_USER: ${DB_USER}
      DB_PASS: ${DB_PASS}
      JWT_SECRET: ${JWT_SECRET}
      RABBIT_USER: ${RABBIT_USER}
      RABBIT_PASS: ${RABBIT_PASS}
      CONFIG_GIT_URI: ${CONFIG_GIT_URI}
      CONFIG_SERVER_USER: ${CONFIG_SERVER_USER}
      CONFIG_SERVER_PASSWORD: ${CONFIG_SERVER_PASSWORD}
      EUREKA_HOST: eureka-server
    ports:
      - "8081:8081"
    depends_on:
      - postgres
      - rabbitmq
      - eureka-server
