server:
  port: 8082

spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/BD_Rocky_Inventarios
    username: postgres
    password: 123456
  jpa:
    hibernate:
      ddl-auto: create-drop

cache:
  type: redis
  ttl: 3600
