spring:
  profiles: prod

management:
  endpoint:
    health:
      show-details: never

logging:
  level:
    root: INFO

    com.libreriarocky.app.usuarios: INFO

    # Spring
    org.springframework: WARN
    org.springframework.web: WARN

    # Hibernate/JPA
    org.hibernate: WARN
    org.hibernate.SQL: WARN

    # RabbitMQ
    org.springframework.amqp: INFO

    # Eureka
    com.netflix.eureka: INFO
    com.netflix.discovery: INFO
